tasks:
  - name: terraform
    before: |
      source ./bin/installing_terraform.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/installing_aws_cli.sh

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform